---
- name: Delete a host from Satellite
  hosts: localhost
  become: false
  vars:
    satellite_ops_content_host_name: "{{ virt_ops_vm_name }}"
  tasks:
    - name: Completely remove host from Satellite
      redhat.satellite.host:
        username: "{{ satellite_ops_username }}"
        password: "{{ satellite_ops_password }}"
        server_url: "{{ satellite_ops_server_url }}"
        validate_certs: "{{ satellite_ops_validate_certs }}"
        name: "{{ satellite_ops_content_host_name }}"
        state: absent