---
- name: Register a host to our Satellite Instance
  hosts: "{{ vm_name | default('none') }}"
  become: true
  vars:
    satellite_ops_activation_key: "{{ satellite_ops_environment }}{{ satellite_ops_server_type }}Hosts"
    rhc_state: present
    rhc_organization: "{{ satellite_ops_org_name }}"
    rhc_auth:
      activation_keys:
        keys: ["{{ satellite_ops_activation_key }}"]
    rhc_insights:
      state: present
      autoupdate: true
  pre_tasks:
    - name: Install the katello ca package from satellite
      ansible.builtin.dnf:
        name: http://{{ satellite_ops_server_name }}/pub/katello-ca-consumer-latest.noarch.rpm
        disable_gpg_check: true
        state: present
  roles:
    - redhat.rhel_system_roles.rhc
