---
- name: Sync a satellite repository
  hosts: "{{ satellite_ops_server_name | default('none') }}"
  gather_facts: false
  tasks:
    - name: Synchronize a Satellite repository
      loop: "{{ satellite_ops_product }}"
      theforeman.foreman.repository_sync:
        username: "{{ satellite_ops_username }}"
        password: "{{ satellite_ops_password }}"
        server_url: "{{ satellite_ops_server_url }}"
        organization: "{{ satellite_ops_org_name }}"
        product: "{{ item }}"
        validate_certs: false
